Adjust wsgi to handle Fieldstorage str vs bytes issue and log errors (#462)
* Adjust wsgi slightly to log any exceptions thrown during the `cgi.Fieldstorage`
parsing of `wsgi.input` under guidance from `environ` values.
Mainly to highlight an issue where wsgi receives content marked as Content-Type
'text/plain' but then fails to parse the corresponding raw binary data from
the `wsgi.input` file descriptor, because it hits the specific code path with
`self.read_single()` in `cgi` where it expects a `str` rather than `bytes`.
This is shown in the added unit tests.

* Rework wsgi and in particular our use of `cgi.FieldStorage` to take the corner-
case with single value instances as seen e.g. if using HTTP PUT or POST with
`content-type` of 'text/plain'.
Basically we patch `cgi.FieldStorage` slightly to address
https://github.com/python/cpython/issues/71964
which won't be fixed upstream because the `cgi` module was deprecated and
retired with python 3.13 before a fix landed.

Minor updates to `bool` vs `is None` tests in conditionals since that is not
supported for single value FieldStorage instances either.
Changed a default `[]` arg value to `None` to avoid common pitfalls like
https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument

Update the unit tests to reflect that we now patch the source of the issue.

* Handle encoding for binary single value case in fieldstorage_to_dict to fix use
on python 3.9 and friends where it will otherwise result in crashes with
```
UnicodeEncodeError: 'ascii' codec can't encode characters in position N-m:
ordinal not in range(128)
```